# Generated by Django 4.2 on 2023-06-06 18:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("computerApp", "0009_alter_machine_maintenancedate"),
    ]

    operations = [
        migrations.AddField(
            model_name="machine",
            name="ip",
            field=models.GenericIPAddressField(null=True),
        ),
        migrations.AddField(
            model_name="machine",
            name="reseau",
            field=models.CharField(
                choices=[
                    ("Filial", "Filial - 192.168.0.0"),
                    ("FAI", "FAI - 10.10.10.0"),
                    ("DMZ", "DMZ - 172.16.0.0"),
                ],
                default="FAI",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="machine",
            name="mach",
            field=models.CharField(
                choices=[
                    ("PC", "PC - Run windows"),
                    ("Mac", "Mac - Run MacOS"),
                    ("Serveur", "Serveur - Simple Server to deploy virtual machines"),
                    ("Switch", "Switch - To maintains and connect servers"),
                    ("Rooter", "Rooter - To maintains and connect LAN"),
                ],
                default="PC",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="machine",
            name="maintenanceDate",
            field=models.DateField(
                default=datetime.datetime(2023, 6, 6, 18, 39, 18, 979063)
            ),
        ),
    ]
