# Generated by Django 4.2 on 2023-05-11 11:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("computerApp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Personnel",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nom", models.CharField(max_length=10)),
                ("prenom", models.CharField(max_length=10)),
                (
                    "pers",
                    models.CharField(
                        choices=[
                            ("utilisateur", "utilisateur - personnel "),
                            ("administrateur", "administrateur - Réseaux"),
                        ],
                        default="utilisateur",
                        max_length=64,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="machine",
            name="mach",
            field=models.CharField(
                choices=[
                    ("PC", "PC - Run windows"),
                    ("Mac", "Mac - Run MacOS"),
                    ("Serveur", "Serveur - Simple Server to deploy virtual machines"),
                    ("Switch", "Switch - To maintains and connect servers"),
                ],
                default="PC",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="machine",
            name="maintenanceDate",
            field=models.DateField(
                default=datetime.datetime(2023, 5, 11, 11, 39, 26, 608717)
            ),
        ),
        migrations.AlterField(
            model_name="machine",
            name="nom",
            field=models.CharField(max_length=6),
        ),
    ]
